<?php

use App\Exceptions\InvalidResumeVariantResponseException;
use App\Models\ResumeVariant;
use App\Support\OllamaChatCompletionsClient;
use App\Support\OllamaChatCompletionsException;
use App\Support\ResumeVariant\Prompts\ResumeWordingPromptV2;
use App\Support\ResumeVariant\ResumeWordingResponseValidator;

/**
 * Opt-in, real-provider check that ResumeWordingPromptV2's contract
 * (system+user prompt, JSON schema, ResumeWordingResponseValidator —
 * including the new location-scoped canonical-Skill-provenance check;
 * see ResumeWordingResponseValidator::assertSkillProvenance()) works
 * against a local Ollama server, as a deliberately controlled A/B
 * against the historical OpenAI wording for the *same* approved
 * evidence plan.
 *
 * Updated from the first live evaluation (which ran against
 * ResumeWordingPromptV1) to ResumeWordingPromptV2 — the targeted
 * Summary clarification added after that first run demonstrated a
 * cross-location canonical-Skill leak (the generated summary named
 * "React"/"Laravel", authorized elsewhere in the same request but not
 * for the summary's own evidence). This run's validator call also now
 * passes real Skill data, so a repeat of that exact failure would be
 * caught deterministically even if the prompt clarification alone
 * doesn't fully prevent it. See
 * docs/resume-variant-generation.md "Skill provenance" for the full
 * investigation.
 *
 * Lives outside phpunit.xml's default testsuites via tests/Pest.php's
 * `->in('Llm')` registration, so it never runs as part of
 * `php artisan test`. Run explicitly, by this exact file path only:
 *
 *     vendor/bin/pest tests/Llm/OllamaResumeWordingFormicLiveTest.php
 *
 * ## Experiment design
 *
 * The only intended variable is the Wording provider/model. Everything
 * upstream is held constant by reusing the exact, already-persisted
 * approved Stage-1 output on ResumeVariant id=2 (Formic, JobMatch id=1,
 * CareerProfile id=1, selection-v1.5/wording-v1.3, both stages
 * generated by openai:gpt-5.6-terra):
 *
 * - `wording_input_snapshot` is replayed verbatim as the user prompt's
 *   approved-selection payload — the identical bytes the historical
 *   OpenAI call received, not a re-derivation.
 * - the deny list, per-location fact keys, guardrail map, approved
 *   (role_id, bullet_group_index) pairs, and approved Selected Project
 *   ids are recomputed from that same row's `selection_raw_response`/
 *   `selection_input_snapshot` using exactly the logic
 *   GenerateResumeVariant::generateFull() applies before its own Stage
 *   2 call (buildDenylistTerms()/buildCareerFactKeysByLocation() and
 *   the `$rolesNeedingWording` block — see that class).
 *
 * That reconstruction was verified before this harness was written by
 * replaying the row's own persisted `wording_raw_response` (the real
 * OpenAI answer) through the current ResumeWordingResponseValidator
 * with these exact reconstructed inputs: it passes. So the inputs
 * below are known to be a faithful reproduction of what Stage 2
 * actually received, and the same yardstick is applied to both
 * providers' answers.
 *
 * **No fresh Resume Selection call is made.** Stage 1 is not re-run,
 * re-validated, or re-generated in any form.
 *
 * Note for interpretation: ResumeVariant id=2's plan was produced by
 * the older `resume-selection-v1.5` prompt and contains 17 approved
 * Experience bullet groups — above the 13-group hard maximum
 * ResumeSelectionPromptV2.1 now enforces. That is correct and
 * deliberate for this experiment (holding the plan constant is the
 * whole point), but it means bullet *count* here reflects the old
 * Selection contract, not what a current Selection run would approve.
 *
 * ## Safety
 *
 * READ-ONLY, real personal data: this harness only ever queries the
 * real dev database, and only ever reads — it never writes to it,
 * never calls GenerateResumeVariant (which would persist a
 * ResumeVariant), and never touches sources/jobs/formic-gtm-engineer.md
 * (that source markdown is not read by any code path here; only
 * already-imported, already-persisted canonical database rows are
 * used). The real dev database connection ('sqlite') is bound to
 * `:memory:` for the whole Pest process per phpunit.xml, so reading
 * the real file requires a second, distinct connection name —
 * registered here at runtime only, never added to config/database.php,
 * and never made `database.default` for longer than the one read below.
 *
 * Exactly ONE Ollama call is made, with no retry beyond the shared
 * transport's own bounded transient-failure retry, no repair, no
 * re-prompt, and no fallback to OpenAI. ZERO OpenAI calls are made:
 * the historical OpenAI wording used for comparison is read from the
 * database, never regenerated.
 *
 * A ResumeWordingResponseValidator failure DOES fail this test (not
 * merely reported) — deliberately, same reasoning as the Selection
 * harness: whether qwen3.8:27b can satisfy the unchanged Wording
 * contract is the primary question this experiment exists to answer.
 *
 * Defaults to omitting reasoning_effort (the model's own default —
 * matching OllamaResumeWordingClient's own production configuration)
 * and that client's production 16,000-token budget; set
 * OLLAMA_LIVE_REASONING_EFFORT and/or
 * OLLAMA_LIVE_RESUME_WORDING_MAX_TOKENS to opt one run into a
 * different configuration, the same one-off-diagnostic env-var pattern
 * the other live harnesses use.
 */
const OLLAMA_RESUME_WORDING_LIVE_EVAL_RESUME_VARIANT_ID = 2; // Formic, real dev database

beforeEach(function () {
    if (blank(config('services.ollama.base_url'))) {
        $this->markTestSkipped('No OLLAMA_BASE_URL configured — skipping live Ollama Resume Wording check.');
    }

    $formicDatabasePath = database_path('database.sqlite');

    if (! file_exists($formicDatabasePath)) {
        $this->markTestSkipped("No dev database found at [{$formicDatabasePath}] — skipping live Ollama Resume Wording check.");
    }
});

it('runs the real Resume Wording prompt/schema through Ollama against the real, already-approved Formic selection plan and reports every pipeline stage', function () {
    $originalConnection = config('database.default');

    // A second, distinct connection name pointed at the real dev
    // database file — registered here only, never persisted to
    // config/database.php. Using a name never previously resolved
    // avoids the stale-cached-PDO problem that reusing 'sqlite' itself
    // would hit (that connection is already bound to phpunit.xml's
    // :memory: for this entire process).
    config(['database.connections.formic_readonly' => [
        'driver' => 'sqlite',
        'database' => database_path('database.sqlite'),
        'prefix' => '',
        'foreign_key_constraints' => true,
    ]]);
    config(['database.default' => 'formic_readonly']);

    $variant = ResumeVariant::findOrFail(OLLAMA_RESUME_WORDING_LIVE_EVAL_RESUME_VARIANT_ID);

    $wordingInput = $variant->wording_input_snapshot;
    $selectionRaw = $variant->selection_raw_response;
    $selectionInput = $variant->selection_input_snapshot;
    $historicalWording = $variant->wording_raw_response;
    $historicalGeneratedBy = $variant->wording_generated_by;
    $jobMatchId = $variant->job_match_id;

    config(['database.default' => $originalConnection]);

    // ---- Reconstruct exactly what GenerateResumeVariant passes to
    // ---- Stage 2 for this same approved plan. See this file's
    // ---- docblock for how this reconstruction was verified.
    $factsByKey = collect($selectionInput['candidate']['career_facts'])->keyBy('key');
    $guardrailByFactKey = $factsByKey->map(fn (array $fact) => $fact['metric']['guardrail'] ?? null)->all();

    // For ResumeWordingResponseValidator::assertSkillProvenance() —
    // mirrors GenerateResumeVariant's own construction of these exactly
    // (see that class). $canonicalSkillsById reuses the already-
    // persisted eligible_skills catalog from this same historical
    // Selection input snapshot, never a fresh Skill::query().
    $skillIdsByFactKey = $factsByKey->map(fn (array $fact) => array_column($fact['skills'], 'id'))->all();
    $canonicalSkillsById = collect($selectionInput['candidate']['eligible_skills'])->pluck('name', 'id')->all();

    // The additive fact-local evidence contract established by the
    // Skill-provenance authority-model investigation — see
    // GenerateResumeVariant's own identical construction and
    // docs/resume-variant-generation.md "Skill provenance". Computed
    // once per fact via the real, shared recognizedSkillIds() method
    // (no second recognition algorithm), never re-scanned per location.
    $textRecognizedSkillIdsByFactKey = $factsByKey->map(function (array $fact) use ($canonicalSkillsById) {
        $evidenceText = trim($fact['statement'].' '.($fact['metric']['scope_note'] ?? '').' '.($fact['metric']['guardrail'] ?? ''));

        return (new ResumeWordingResponseValidator)->recognizedSkillIds($evidenceText, $canonicalSkillsById);
    })->all();

    $rolesNeedingWording = collect($selectionRaw['experience'])->filter(fn (array $role) => $role['bullet_groups'] !== []);
    $rolesInSelection = $rolesNeedingWording->pluck('role_id')->all();
    $expectedBulletGroupIndexesByRole = $rolesNeedingWording
        ->mapWithKeys(fn (array $role) => [$role['role_id'] => array_keys($role['bullet_groups'])])
        ->all();
    $selectedProjectIds = collect($selectionRaw['selected_projects'])->pluck('project_id')->all();

    $validTargetTerms = array_column($selectionInput['target_terminology'], 'term');
    $directTerms = collect($selectionRaw['target_term_usages'])
        ->filter(fn (array $usage) => $usage['posture'] === 'direct')
        ->pluck('term')
        ->all();
    $denylistTerms = array_values(array_diff($validTargetTerms, $directTerms));

    $careerFactKeysByLocation = ['summary' => $selectionRaw['summary_evidence']];
    foreach ($selectionRaw['experience'] as $role) {
        foreach ($role['bullet_groups'] as $index => $group) {
            $careerFactKeysByLocation["{$role['role_id']}:{$index}"] = $group['career_fact_keys'];
        }
    }
    foreach ($selectionRaw['selected_projects'] as $project) {
        $careerFactKeysByLocation["project:{$project['project_id']}"] = $project['career_fact_keys'];
    }
    foreach ($selectionRaw['target_term_usages'] as $usage) {
        $key = $usage['location_type'] === 'bullet'
            ? "{$usage['role_id']}:{$usage['bullet_group_index']}"
            : 'summary';
        $careerFactKeysByLocation[$key] = array_values(array_unique([
            ...($careerFactKeysByLocation[$key] ?? []),
            ...$usage['career_fact_keys'],
        ]));
    }

    $prompt = new ResumeWordingPromptV2;
    $schema = $prompt->jsonSchema($rolesInSelection, $selectedProjectIds);

    $transport = new OllamaChatCompletionsClient;
    $validator = new ResumeWordingResponseValidator;

    $reasoningEffort = getenv('OLLAMA_LIVE_REASONING_EFFORT') ?: null;
    $maxOutputTokens = getenv('OLLAMA_LIVE_RESUME_WORDING_MAX_TOKENS')
        ? (int) getenv('OLLAMA_LIVE_RESUME_WORDING_MAX_TOKENS')
        : 16000; // must track OllamaResumeWordingClient::MAX_OUTPUT_TOKENS

    $expectedBulletCount = collect($expectedBulletGroupIndexesByRole)->flatten()->count();

    $report = [
        'resume_variant_id' => OLLAMA_RESUME_WORDING_LIVE_EVAL_RESUME_VARIANT_ID,
        'job_match_id' => $jobMatchId,
        'provider' => 'ollama',
        'configured_model' => config('services.ollama.resume_wording_model'),
        'returned_model' => null,
        'reasoning_effort_requested' => $reasoningEffort,
        'max_tokens_requested' => $maxOutputTokens,
        'timeout_seconds' => (int) config('services.ollama.resume_wording_timeout'),
        'elapsed_seconds' => null,
        'finish_reason' => null,
        'prompt_tokens' => null,
        'completion_tokens' => null,
        'total_tokens' => null,
        'wording_prompt_version' => $prompt->version(),
        'wording_schema_version' => $prompt->schemaVersion(),
        'approved_roles' => count($rolesInSelection),
        'approved_bullet_groups' => $expectedBulletCount,
        'approved_selected_projects' => count($selectedProjectIds),
        'summary_evidence_facts' => count($wordingInput['summary_evidence']),
        'denylist_terms' => $denylistTerms,
        'guardrail_bearing_supplied_facts' => collect($guardrailByFactKey)->filter()->count(),
        'canonical_skills_recognized' => count($canonicalSkillsById),
        'system_prompt_chars' => strlen($prompt->systemPrompt()),
        'user_prompt_chars' => strlen($prompt->userPrompt($wordingInput, $denylistTerms)),
        'openai_baseline' => [
            'generated_by' => $historicalGeneratedBy,
            'bullets' => collect($historicalWording['experience'])->sum(fn (array $r) => count($r['bullets'])),
            'summary_words' => resumeWordingWordCount($historicalWording['summary']),
        ],
        'structured_decode' => null,
        'validator' => null,
    ];

    $start = microtime(true);

    try {
        $result = $transport->call(
            baseUrl: (string) config('services.ollama.base_url'),
            model: (string) config('services.ollama.resume_wording_model'),
            systemPrompt: $prompt->systemPrompt(),
            userPrompt: $prompt->userPrompt($wordingInput, $denylistTerms),
            schema: $schema,
            schemaName: 'resume_wording',
            maxOutputTokens: $maxOutputTokens,
            timeoutSeconds: (int) config('services.ollama.resume_wording_timeout'),
            logPrefix: 'Resume Wording generation (Ollama live check)',
            reasoningEffort: $reasoningEffort,
        );
    } catch (OllamaChatCompletionsException $e) {
        $report['elapsed_seconds'] = round(microtime(true) - $start, 2);
        $report['returned_model'] = $e->model;
        $report['finish_reason'] = $e->finishReason;
        $report['prompt_tokens'] = $e->usage['prompt_tokens'] ?? null;
        $report['completion_tokens'] = $e->usage['completion_tokens'] ?? null;
        $report['total_tokens'] = $e->usage['total_tokens'] ?? null;
        $report['structured_decode'] = 'FAILED (transport)';
        printResumeWordingReport($report);

        // STOP: no retry, no max_tokens change, no repair, no second call.
        throw $e;
    }

    $report['elapsed_seconds'] = round(microtime(true) - $start, 2);
    $report['returned_model'] = $result->model;
    $report['finish_reason'] = $result->finishReason;
    $report['prompt_tokens'] = $result->usage['prompt_tokens'] ?? null;
    $report['completion_tokens'] = $result->usage['completion_tokens'] ?? null;
    $report['total_tokens'] = $result->usage['total_tokens'] ?? null;
    $report['structured_decode'] = 'OK';

    try {
        $validated = $validator->validate(
            $result->structuredContent,
            $rolesInSelection,
            $expectedBulletGroupIndexesByRole,
            $selectedProjectIds,
            $denylistTerms,
            $careerFactKeysByLocation,
            $guardrailByFactKey,
            $skillIdsByFactKey,
            $canonicalSkillsById,
            $textRecognizedSkillIdsByFactKey,
        );
    } catch (InvalidResumeVariantResponseException $e) {
        $report['validator'] = 'FAILED';
        printResumeWordingReport($report);
        fwrite(STDERR, "\n=== Ollama Resume Wording live check: VALIDATION FAILED ===\n".$e->getMessage().PHP_EOL);
        printResumeWordingStructuredContent($e->context ?? $result->structuredContent);

        // STOP: no retry, no repair, no second call.
        throw $e;
    }

    $report['validator'] = 'PASSED';

    printResumeWordingReport($report);
    printResumeWordingStructuredContent($validated);
    printResumeWordingEvidencePairing($validated, $wordingInput, $careerFactKeysByLocation, $factsByKey->all());
    printResumeWordingOpenAIComparison($validated, $historicalWording, $historicalGeneratedBy);

    // Only transport/decode/validation are asserted on — everything in
    // the evidence-pairing and comparison sections is surfaced for
    // human review, never asserted, per this file's docblock.
    expect($validated['experience'])->not->toBeEmpty();
});

function resumeWordingWordCount(string $text): int
{
    $words = preg_split('/\s+/u', trim($text));

    return $words === false ? 0 : count(array_filter($words, fn (string $word) => $word !== ''));
}

/**
 * @param  array<string, mixed>  $report
 */
function printResumeWordingReport(array $report): void
{
    fwrite(STDERR, "\n".'=== Ollama Resume Wording live check: report ==='."\n".json_encode($report, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL);
}

/**
 * @param  array<string, mixed>  $structuredContent
 */
function printResumeWordingStructuredContent(array $structuredContent): void
{
    fwrite(STDERR, "\n".'=== Ollama Resume Wording live check: structured content ==='."\n".json_encode($structuredContent, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE).PHP_EOL);
}

/**
 * Pairs every generated sentence with the exact evidence supplied for
 * it. Metric fidelity and technology provenance are deliberately NOT
 * deterministically enforced by ResumeWordingResponseValidator (see its
 * docblock) — this section exists so a human can check them directly
 * rather than inferring them, and is the primary reason this harness
 * prints as much as it does.
 *
 * @param  array<string, mixed>  $validated
 * @param  array<string, mixed>  $wordingInput
 * @param  array<string, array<int, string>>  $careerFactKeysByLocation
 * @param  array<string, array<string, mixed>>  $factsByKey
 */
function printResumeWordingEvidencePairing(array $validated, array $wordingInput, array $careerFactKeysByLocation, array $factsByKey): void
{
    $lines = [];

    $lines[] = '--- SUMMARY ---';
    $lines[] = 'generated: '.$validated['summary'];
    $lines[] = 'word_count: '.resumeWordingWordCount($validated['summary']);
    $lines[] = 'supplied evidence:';
    foreach ($wordingInput['summary_evidence'] as $fact) {
        $lines[] = '  - ['.$fact['key'].'] '.$fact['statement'];
        $lines[] = '    metric: '.json_encode($fact['metric'], JSON_UNESCAPED_SLASHES);
        $lines[] = '    skills: '.json_encode(array_column($fact['skills'], 'name'), JSON_UNESCAPED_SLASHES);
    }

    $suppliedByLocation = [];
    foreach ($wordingInput['experience'] as $role) {
        foreach ($role['bullet_groups'] as $group) {
            $suppliedByLocation["{$role['role_id']}:{$group['bullet_group_index']}"] = $group['career_facts'];
        }
    }

    $lines[] = '';
    $lines[] = '--- EXPERIENCE BULLETS ---';
    foreach ($validated['experience'] as $role) {
        foreach ($role['bullets'] as $bullet) {
            $location = "{$role['role_id']}:{$bullet['bullet_group_index']}";
            $lines[] = '';
            $lines[] = "role_id={$role['role_id']} bullet_group_index={$bullet['bullet_group_index']}";
            $lines[] = 'generated: '.$bullet['text'];
            $lines[] = 'word_count: '.resumeWordingWordCount($bullet['text']);
            $lines[] = 'cited career_fact_keys: '.json_encode($careerFactKeysByLocation[$location] ?? [], JSON_UNESCAPED_SLASHES);
            $lines[] = 'supplied evidence:';
            foreach ($suppliedByLocation[$location] ?? [] as $fact) {
                $lines[] = '  - ['.$fact['key'].'] '.$fact['statement'];
                $lines[] = '    metric: '.json_encode($fact['metric'], JSON_UNESCAPED_SLASHES);
                $lines[] = '    skills: '.json_encode(array_column($fact['skills'], 'name'), JSON_UNESCAPED_SLASHES);
            }
        }
    }

    $suppliedByProject = [];
    foreach ($wordingInput['selected_projects'] as $project) {
        $suppliedByProject[$project['project_id']] = $project['career_facts'];
    }

    $lines[] = '';
    $lines[] = '--- SELECTED PROJECTS ---';
    foreach ($validated['selected_projects'] as $project) {
        $lines[] = '';
        $lines[] = "project_id={$project['project_id']}";
        $lines[] = 'generated: '.$project['text'];
        $lines[] = 'word_count: '.resumeWordingWordCount($project['text']);
        $lines[] = 'supplied evidence:';
        foreach ($suppliedByProject[$project['project_id']] ?? [] as $fact) {
            $lines[] = '  - ['.$fact['key'].'] '.$fact['statement'];
            $lines[] = '    metric: '.json_encode($fact['metric'], JSON_UNESCAPED_SLASHES);
            $lines[] = '    skills: '.json_encode(array_column($fact['skills'], 'name'), JSON_UNESCAPED_SLASHES);
        }
    }

    fwrite(STDERR, "\n".'=== Ollama Resume Wording live check: generated prose vs. supplied evidence ==='."\n".implode("\n", $lines).PHP_EOL);
}

/**
 * Side-by-side against the historical OpenAI wording for the exact
 * same approved plan. OpenAI is NOT ground truth — it is one
 * independent, already-human-accepted answer to the identical
 * question, useful for noticing systematic differences. No score, no
 * winner: differences are surfaced for human judgment.
 *
 * @param  array<string, mixed>  $validated
 * @param  array<string, mixed>  $historical
 */
function printResumeWordingOpenAIComparison(array $validated, array $historical, string $historicalGeneratedBy): void
{
    $lines = [];
    $lines[] = "Comparison baseline: {$historicalGeneratedBy} (historical, already-human-accepted).";
    $lines[] = 'OpenAI is NOT ground truth — it is a second answer to the identical approved plan.';
    $lines[] = '';

    $qwenSummaryWords = resumeWordingWordCount($validated['summary']);
    $openaiSummaryWords = resumeWordingWordCount($historical['summary']);
    $lines[] = '--- SUMMARY ---';
    $lines[] = "qwen   ({$qwenSummaryWords} words): ".$validated['summary'];
    $lines[] = "openai ({$openaiSummaryWords} words): ".$historical['summary'];

    $historicalByLocation = [];
    foreach ($historical['experience'] as $role) {
        foreach ($role['bullets'] as $bullet) {
            $historicalByLocation["{$role['role_id']}:{$bullet['bullet_group_index']}"] = $bullet['text'];
        }
    }

    $qwenCounts = [];
    $lines[] = '';
    $lines[] = '--- EXPERIENCE BULLETS, SAME APPROVED PLAN, SIDE BY SIDE ---';
    foreach ($validated['experience'] as $role) {
        foreach ($role['bullets'] as $bullet) {
            $location = "{$role['role_id']}:{$bullet['bullet_group_index']}";
            $qwenWords = resumeWordingWordCount($bullet['text']);
            $qwenCounts[] = $qwenWords;
            $openaiText = $historicalByLocation[$location] ?? '(no historical bullet at this location)';
            $openaiWords = is_string($openaiText) ? resumeWordingWordCount($openaiText) : 0;
            $lines[] = '';
            $lines[] = "[{$location}]";
            $lines[] = "  qwen   ({$qwenWords} words): ".$bullet['text'];
            $lines[] = "  openai ({$openaiWords} words): ".$openaiText;
        }
    }

    $historicalCounts = [];
    foreach ($historical['experience'] as $role) {
        foreach ($role['bullets'] as $bullet) {
            $historicalCounts[] = resumeWordingWordCount($bullet['text']);
        }
    }

    $historicalProjectsById = [];
    foreach ($historical['selected_projects'] as $project) {
        $historicalProjectsById[$project['project_id']] = $project['text'];
    }

    $lines[] = '';
    $lines[] = '--- SELECTED PROJECTS, SIDE BY SIDE ---';
    foreach ($validated['selected_projects'] as $project) {
        $lines[] = '';
        $lines[] = "[project_id={$project['project_id']}]";
        $lines[] = '  qwen  : '.$project['text'];
        $lines[] = '  openai: '.($historicalProjectsById[$project['project_id']] ?? '(none)');
    }

    $lines[] = '';
    $lines[] = '--- LENGTH DISTRIBUTION (descriptive only, not a quality verdict) ---';
    $lines[] = 'qwen   bullets: n='.count($qwenCounts)
        .' min='.(count($qwenCounts) > 0 ? min($qwenCounts) : 0)
        .' max='.(count($qwenCounts) > 0 ? max($qwenCounts) : 0)
        .' avg='.(count($qwenCounts) > 0 ? round(array_sum($qwenCounts) / count($qwenCounts), 1) : 0);
    $lines[] = 'openai bullets: n='.count($historicalCounts)
        .' min='.(count($historicalCounts) > 0 ? min($historicalCounts) : 0)
        .' max='.(count($historicalCounts) > 0 ? max($historicalCounts) : 0)
        .' avg='.(count($historicalCounts) > 0 ? round(array_sum($historicalCounts) / count($historicalCounts), 1) : 0);

    $lines[] = '';
    $lines[] = '--- HUMAN REVIEW CHECKLIST (read the pairing section above against each) ---';
    foreach ([
        'clarity — is each bullet immediately understandable to a recruiter?',
        'concision — any padding, filler, or restatement?',
        'specificity — concrete systems/outcomes, or generic praise?',
        'action/result structure — does each bullet land on something achieved?',
        'verb repetition — consecutive or majority-share repeated openers within a role?',
        'keyword stuffing — terminology inserted awkwardly rather than naturally?',
        'metric fidelity — does every stated figure match its supplied Metric exactly (value, unit, comparator, scope_note)?',
        'metric attachment — is each figure attached to the accomplishment it actually belongs to?',
        'technology fidelity — is every named technology present in that bullet\'s own supplied facts/skills?',
        'ownership language — does any verb imply more ownership than the evidence states?',
        'unsupported causal language — any "resulting in"/"driving" claim the evidence does not establish?',
        'factual nuance — are hedges, scopes, and qualifiers in the source preserved?',
        'foregrounding — was the strongest supplied evidence led with, or buried?',
        'emphasis drift — did the model silently reinterpret what a bullet group is about?',
        'hallucination — anything stated that appears in no supplied fact at all?',
    ] as $item) {
        $lines[] = '  - '.$item;
    }

    fwrite(STDERR, "\n".'=== Ollama Resume Wording live check: qwen vs. historical OpenAI (surfaced, not asserted) ==='."\n".implode("\n", $lines).PHP_EOL);
}
